import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { fetchSystemInfo } from '../services/api';
import { initialEntries } from '../data/initialData';

// Neovim-inspired theme colors
const THEME = {
  // Base colors
  bg: {
    primary: '#1e1e2e',    // Main background (like Neovim's background)
    secondary: '#181825',  // Secondary background (like Neovim's statusline)
    tertiary: '#313244',   // Tertiary background (like Neovim's visual selection)
  },
  fg: {
    primary: '#cdd6f4',    // Primary text (like Neovim's foreground)
    secondary: '#a6adc8',  // Secondary text (like Neovim's comment)
    muted: '#6c7086',      // Muted text (like Neovim's line numbers)
  },
  accent: {
    blue: '#89b4fa',       // Like Neovim's blue
    green: '#a6e3a1',      // Like Neovim's green
    red: '#f38ba8',        // Like Neovim's red
    yellow: '#f9e2af',     // Like Neovim's yellow
    purple: '#cba6f7',     // Like Neovim's purple
    orange: '#fab387',     // Like Neovim's orange
  },
  border: {
    primary: '#313244',    // Primary border color
    secondary: '#45475a',  // Secondary border color
  }
};

interface SystemInfo {
  system: {
    hostname: string;
    baseInstall: string;
    kernel: string;
    bootloader: string;
    loginManager: string;
    font: string;
    theme: string;
    iconTheme: string;
    cursorTheme: string;
  };
  users: string[];
  drivers: {
    graphics: string;
    audio: string;
  };
  packages: {
    coreOsUtilities: string[];
    extraUtilities: string[];
    webBrowsers: string[];
    textEditors: string[];
    launchers: string[];
    applications: string[];
  };
  themes: {
    fonts: string[];
    themes: string[];
    iconThemes: string[];
    cursorThemes: string[];
  };
}

interface User {
  id: string;
  username: string;
  isRoot: boolean;
}

interface AppContextType {
  systemInfo: SystemInfo;
  entries: any[];
  users: User[];
  addUser: (user: Omit<User, 'id'>) => void;
  removeUser: (username: string) => void;
  theme: typeof THEME;
  refreshSystemInfo: () => Promise<void>;
  addEntry: (entry: any) => void;
  generateInstallScript: (categories?: string[]) => string;
}

const defaultSystemInfo: SystemInfo = {
  system: {
    hostname: 'Loading...',
    baseInstall: 'Loading...',
    kernel: 'Loading...',
    bootloader: 'Loading...',
    loginManager: 'Loading...',
    font: 'Loading...',
    theme: 'Loading...',
    iconTheme: 'Loading...',
    cursorTheme: 'Loading...'
  },
  users: [],
  drivers: {
    graphics: 'Loading...',
    audio: 'Loading...'
  },
  packages: {
    coreOsUtilities: [],
    extraUtilities: [],
    webBrowsers: [],
    textEditors: [],
    launchers: [],
    applications: []
  },
  themes: {
    fonts: [],
    themes: [],
    iconThemes: [],
    cursorThemes: []
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [systemInfo, setSystemInfo] = useState<SystemInfo>(defaultSystemInfo);
  const [users, setUsers] = useState<User[]>([]);
  const [entries, setEntries] = useState<any[]>(initialEntries);

  useEffect(() => {
    loadSystemInfo();
  }, []);

  const loadSystemInfo = async () => {
    try {
      const info = await fetchSystemInfo();
      setSystemInfo(info);
    } catch (error) {
      console.error('Failed to load system info:', error);
    }
  };

  const refreshSystemInfo = async () => {
    await loadSystemInfo();
    setEntries(initialEntries);
  };

  const addUser = (user: Omit<User, 'id'>) => {
    setUsers(prev => [...prev, { ...user, id: Math.random().toString(36).substr(2, 9) }]);
  };

  const removeUser = (username: string) => {
    setUsers(prev => prev.filter(user => user.username !== username));
  };

  const addEntry = (entry: any) => {
    setEntries(prev => [...prev, { ...entry, id: Math.random().toString(36).substr(2, 9) }]);
  };

  const generateInstallScript = (categories?: string[]) => {
    // Filter entries by selected categories if provided
    const filteredEntries = categories 
      ? entries.filter(entry => categories.includes(entry.category))
      : entries;

    // Group entries by category
    const entriesByCategory = filteredEntries.reduce((acc, entry) => {
      if (!acc[entry.category]) {
        acc[entry.category] = [];
      }
      acc[entry.category].push(entry);
      return acc;
    }, {} as Record<string, typeof entries[]>);

    // Get AUR packages
    const aurPackages = filteredEntries
      .filter(entry => entry.packageName && entry.isInstalled && entry.category === 'aur')
      .map(entry => entry.packageName)
      .join(' ');

    // Generate the script content
    const script = `#!/bin/bash

# Generated by Arch Linux System Manager
# ${new Date().toLocaleString()}

# Exit on error
set -e

# Function to print status messages
print_status() {
    echo -e "\\033[1;34m==>\\033[0m $1"
}

print_error() {
    echo -e "\\033[1;31mError:\\033[0m $1"
    exit 1
}

print_success() {
    echo -e "\\033[1;32mSuccess:\\033[0m $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root"
fi

# Update system
print_status "Updating system..."
pacman -Syu --noconfirm || print_error "Failed to update system"

# Install yay if not present
if ! command -v yay &> /dev/null; then
    print_status "Installing yay..."
    pacman -S --needed git base-devel --noconfirm || print_error "Failed to install base packages"
    sudo -u $SUDO_USER git clone https://aur.archlinux.org/yay.git /tmp/yay || print_error "Failed to clone yay"
    cd /tmp/yay
    sudo -u $SUDO_USER makepkg -si --noconfirm || print_error "Failed to build yay"
    cd -
fi

# Install packages by category
${Object.entries(entriesByCategory).map(([category, categoryEntries]) => {
  const categoryName = categories?.find(c => c === category) || category;
  const packages = (categoryEntries as typeof entries[])
    .filter(entry => entry.packageName && entry.isInstalled)
    .map(entry => entry.packageName)
    .join(' ');

  if (!packages) return '';

  return `
# ${categoryName}
print_status "Installing ${categoryName} packages..."
pacman -S --noconfirm ${packages} || print_error "Failed to install ${categoryName} packages"`;
}).filter(Boolean).join('\n')}

${aurPackages ? `
# AUR Packages
print_status "Installing AUR packages..."
yay -S --noconfirm ${aurPackages} || print_error "Failed to install AUR packages"` : ''}

# Configuration steps
print_status "Applying configurations..."

# Create necessary directories
mkdir -p ~/.config/hypr
mkdir -p ~/.config/waybar
mkdir -p ~/.config/wofi

# Copy configuration files if they exist
if [ -f "/usr/share/hyprland/hyprland.conf" ]; then
    cp /usr/share/hyprland/hyprland.conf ~/.config/hypr/
fi

# Enable services
print_status "Enabling services..."
systemctl enable --user pipewire.service
systemctl enable --user pipewire-pulse.service
systemctl enable --user wireplumber.service

print_success "Installation complete!"
`;

    return script;
  };

  return (
    <AppContext.Provider value={{
      systemInfo,
      entries,
      users,
      addUser,
      removeUser,
      theme: THEME,
      refreshSystemInfo,
      addEntry,
      generateInstallScript
    }}>
      {children}
    </AppContext.Provider>
  );
};

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}